name: Hello
on: 
  workflow_dispatch: 
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful world
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world. ${{inputs.greeting}}"
      - uses: actions/checkout@v4