name: variables
run-name: Run by @${{github.actor}}
on: push
jobs:
  konnichinko:
    name: uoooooooo
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{vars.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      # - run: printenv | grep '_FUNC'
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
      - id: resource
        run: echo "ass=fucking" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.resource.output.ass }}
        run: echo "${RESULT}"