name: variables
on: push
jobs:
  konnichinko:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{vars.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - run: printenv | grep '_FUNC'
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"